



services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\UsersAuthenticator:
        arguments:
            $urlGenerator: '@router'
        tags:
            - { name: 'security.authenticator' }

   # config/services.yaml

    # Vous pouvez définir des services ici
    # Par exemple :
    # App\Service\SomeService:
    #     arguments: ['@some_other_service']
    
    # Autoconfigure et autowire toutes les classes dans src/
    # Il est habituel de ne pas avoir besoin d'une configuration spécifique pour ces classes
   
  
        # Vous pouvez ajouter d'autres configurations si nécessaire
       
   
    App\Repository\CategoriesRepository:
        arguments:
            $registry: '@doctrine'

    # Pour les services de votre application
    # Vous pouvez les ajouter ici avec des définitions spécifiques
       
    App\Repository\UsersRepository:
        arguments:
            $registry: '@doctrine'

    App\Controller\Admin\ProductsController:
        arguments:
            $someService: '@some_service' 
            $productsRepository: '@App\Repository\ProductsRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $slugger: '@slugger'
            $pictureService: '@App\Service\PictureService\PictureService' # Replace with your actual services
        tags:
            - { name: 'controller.service_arguments' }
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller_service']

       
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Repository,Kernel.php}'
   
          
         
  
    
    App\Service\PictureService\PictureService:
        arguments:
            $params: '@parameter_bag'
            $logger: '@logger'

    App\Repository\ProductsRepository:
        tags: ['doctrine.repository_service']

    




       

    